'use client';

import { Button } from '@/components/ui/button';
import { ArrowRight, Sparkles } from 'lucide-react';

export function Hero() {
  return (
    <section className="relative overflow-hidden pt-24 pb-32 md:pt-32 md:pb-40">
      {/* Background gradient */}
      <div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(59,130,246,0.15),rgba(255,255,255,0))]" />

      <div className="container mx-auto px-4 md:px-6">
        <div className="flex flex-col items-center text-center max-w-4xl mx-auto">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 rounded-full border border-border bg-secondary/50 px-4 py-1.5 text-sm font-medium mb-8">
            <Sparkles className="h-4 w-4 text-primary" />
            AI-Powered Design System Generator
          </div>

          {/* Headline */}
          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight text-foreground mb-6">
            From idea to{' '}
            <span className="text-primary">pixel-perfect</span> UI
          </h1>

          {/* Subheadline */}
          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mb-10">
            Transform your business ideas into production-ready Figma designs.
            Content strategy, design tokens, and components — all generated by AI.
          </p>

          {/* CTAs */}
          <div className="flex flex-col sm:flex-row gap-4">
            <Button size="xl" className="group">
              Start Building
              <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" />
            </Button>
            <Button variant="outline" size="xl">
              See How It Works
            </Button>
          </div>

          {/* Social proof */}
          <div className="mt-16 flex flex-col items-center gap-4">
            <p className="text-sm text-muted-foreground">
              Trusted by designers and developers at
            </p>
            <div className="flex items-center gap-8 opacity-50">
              <span className="text-xl font-semibold">Vercel</span>
              <span className="text-xl font-semibold">Stripe</span>
              <span className="text-xl font-semibold">Linear</span>
              <span className="text-xl font-semibold">Notion</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
